version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3

    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ansible
  deploy:
    docker:
      - image: circleci/python:3.7.7

    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3 
      - run:
          command: wget 'https://raw.githubusercontent.com/mdok/depend/master/presentation1.pem?token=AHXYYBHHIVTDOHG6IQ6PZZC6XBENC' -O presentation1.pem && chmod 400 presentation1.pem &&  ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ec2_deploy.yml --user ubuntu --key-file key_file.txt

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
