version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3

    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: circleci/python:3.7.7

    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3 
      - run:
          command: cd /ansible && chmod 400 ~/.ssh/ec2 &&  ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook ec2_deploy.yml --user ubuntu --key-file ~/.ssh/ec2

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
