version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3

    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ansible
  deploy:
    docker:
      - image: circleci/python:3.7.7

    steps:
      - add_ssh_keys:
          fingerprints:
            - "1c:b4:33:72:c7:03:82:27:5d:27:5f:90:26:f5:f0:50"
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3 
      - run:
          command: cd /ansible && ansible-playbook ec2_deploy.yml --user ubuntu 

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
