vse: &vse
  docker:
    - image: circleci/node:8.11.3

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: docker build -t ansible:latest -f Dockerfile_ansible /.circleci/Dockerfile_ansible
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: *vse
    steps:
      - attach_workspace:
          at: .
      - run: docker run ansible
      - run:
          command: cd ansibled && echo $key > key_file.txt &&  ansible-playbook ec2_deploy.yml --user ubuntu --key-file key_file.txt

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
